branches:
  only: src
language: python
python: '2.7'
sudo: false
env:
  global:
  - secure: O9hWgF2x5zNTK89JxQWYtseQGAp0isX8TxRL9N+dvp9sJLy7rE8wu5cpJD47AQVcdqaTe6xkVdN9QkdwBBHRYN42JcZ8C1sPNTMtyPSL9Hud5Duwh62PxE0cF13Y0okLqE/YaCXQvG1q/HTpWU3jT8+GNIVXHpA8hJ6r7jjooUw=
cache: pip
before_script: gem install sass -v 3.4.25
script: pelican -s publishconf.py
after_success: ./generate.sh deploy
