#!/bin/bash

upload() {
	outputPath=${rootPath}/output
	pelican -q -s settings.py

	cd $outputPath
	cp ../favicon.ico favicon.ico
	cp ../robots.txt robots.txt
	cp -R ../uploads/ uploads/
	find . -name '*.DS_Store' -type f -delete || echo "Error deleting .DS_Store files."
	echo "kevinyap.ca" > CNAME

	printf "\e[0;32mSite generated successfully.\e[0m\n"

	cd $rootPath
	commitHash=$(git rev-parse HEAD)

	cd $outputPath
	git checkout master
	git add -A
	wait && read -p "Extended commit message: " commitMessage
	if [ -z "$commitMessage" ]; then
		git commit -m "Generated by $commitHash"
	else
		git commit -m "Generated by $commitHash" -m "$commitMessage"
	fi
	git push
}

preview() {
	outputPath=${rootPath}/preview
	pelican -s preview.py

	cd $outputPath
	cp ../favicon.ico favicon.ico
	cp -R ../uploads/ uploads/
	printf "\e[0;32mSite generated successfully.\e[0m\n"
	python -m SimpleHTTPServer
	cd $rootPath
	rm -rf preview
}

# Implpementation

rootPath="$HOME/kevinyap.ca"
cd $rootPath

if [[ $1 = "-p" ]]; then
	preview
elif [[ $1 = "-u" ]]; then
	upload
else
	read -n1 -p "Preview or upload site? [P/U] " input
	printf "\n"

	case $input in
	  p|P)
	    preview ;;
	  u|U)
	    upload ;;
	  *)
	    printf "Unknown input.\n"
	    exit 1
	esac
fi
