#!/bin/bash

rootPath="$HOME/kevinyap.ca"
outputPath=${rootPath}/output

cd $rootPath
pelican -q -s settings.py

# Run file copying/deletion commands
cd $outputPath
cp ../favicon.ico favicon.ico
cp ../robots.txt robots.txt
cp ../CNAME CNAME
cp -R ../uploads/ uploads/
find . -name '*.DS_Store' -type f -delete || echo "Error deleting .DS_Store files."

printf "\e[0;32mSite generated successfully.\e[0m\n"

if [ -z "$1" ]; then # no flag
	exit
elif [ $1 = "-p" ]; then
	python -m SimpleHTTPServer
elif [ $1 = "-u" ]; then
	cd $rootPath
	commitHash=$(git rev-parse HEAD)

	cd $outputPath
	git checkout master
	git add -A
	read -p "Extended commit message: " commitMessage
	if [ -z "$commitMessage" ]; then
		git commit -m "Generated by $commitHash"
	else
		git commit -m "Generated by $commitHash" -m "$commitMessage"
	fi
	git push
fi
