name: Pelican Build
on:
  push:
    branches:
      - src
permissions:
  contents: write
jobs:
  pelican-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: make install
      
      - name: Build Site
        run: make build
      
      - name: Deploy from src
        uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/src' && github.event_name != 'pull_request'
        with:
          folder: output # The folder the action should deploy.
   
      - name: Display Diff
        if: !(github.ref == 'refs/heads/src' && github.event_name != 'pull_request)
        run: make diff
